# Dockerfile.cart

# Use the official Python image as a base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5003 to the outside world
EXPOSE 5003

# Run the cart Flask application directly
CMD ["python", "cart.py"]

